### ISSUE TITLE
test can't be run in intellij

### ISSUE THREAD

**Issue by notyy** [scala-js/scala-js-website#119]
hi, 

my plugin.scala
```scala
addSbtPlugin("org.scala-lang.modules.scalajs" %% "scalajs-sbt-plugin" % "0.5.6")

addSbtPlugin("com.lihaoyi" % "utest-js-plugin" % "0.2.3")
```
I followed tutorial to step 6,  sbt test works fine, but when run TutorialAppTest inside intellij,  error occurs:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.runTestSuites(UTestRunner.java:187)
	at org.jetbrains.plugins.scala.testingSupport.uTest.UTestRunner.main(UTestRunner.java:254)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:225)
	at org.scalajs.jquery.package$.<init>(package.scala:6)
	at org.scalajs.jquery.package$.<clinit>(package.scala)
	at scalajs.TutorialApp$.setupUI(TutorialApp.scala:22)
	at scalajs.TutorialAppTest$.<init>(TutorialAppTest.scala:10)
	at scalajs.TutorialAppTest$.<clinit>(TutorialAppTest.scala:13)
	at scalajs.TutorialAppTest.tests(TutorialAppTest.scala)
	... 11 more
```

**Comment by sjrd** [comment]
There's nothing we can do about that. Running and testing most be done in sbt. The IDEs don't know about Scala.js specifically, so they don't know how to run us.
